version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
  web:
    env_file: 
      - .env
    build: .
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
